### ISSUE TITLE
Fix logo choose file alignment on dataset creation page

### ISSUE THREAD

**Issue by mrueschman** [nsrr/www.sleepdata.org#324]
E.g.

![image](https://user-images.githubusercontent.com/707167/43837517-c73ff510-9ae6-11e8-86e0-633a674e0115.png)

**Comment by remomueller** [comment]
This is actually due to Bootstrap 4 gem updating how file fields are done, here's how it was fixed in MyApnea for reference:

Markup for file field changed:
https://github.com/myapnea/www.myapnea.org/commit/401536820c051e393222d3febec6de8d59563a47#diff-5ab7d4e15b9b9de61ce773fd5c0517ab

Custom JS Required:
https://github.com/myapnea/www.myapnea.org/commit/e183cbeecc3284fc5177dbe6e4829c5a6b3e571b#diff-edf8725d7cb9e20910956653ec6eb4c4

**Comment by remomueller** [comment]
Also here's what it looks like with the new styling:

![screen shot 2018-08-08 at 9 42 02 am](https://user-images.githubusercontent.com/316479/43840723-59ef6956-9aef-11e8-9bbf-c53cba1ec6c1.png)

**Comment by remomueller** [comment]
Same fix in Slice: https://github.com/remomueller/slice/commit/0ff2bbf74b982e052eccfb5481fb9b8eba171d49
